### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by AndreasBoehm** [schlimmchen/dummytobemoved#12] opened 2024-09-24 19:10 UTC
### What happened?

Everything

### To Reproduce Bug

Hmm

### Expected Behavior

Different

### Install Method

Pre-Compiled binary from GitHub releases

### What git-hash/version of OpenDTU?

358;:(

### What firmware variant (PIO Environment) are you using?

Genetic

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of OpenDTU-OnBattery, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.
- [X] I have double checked that my inverter does not contain a W in the model name (like HMS-xxxW) as they are not supported.

**Comment by schlimmchen** [comment] 2024-09-24 19:11
That's not a bug... Closing.

**Closed by schlimmchen** 2024-09-24 19:11 UTC
Labels: bug
